[project]
name = "qubes-doc"
version = "4.2"
description = "Qubes OS documentation"
authors = [
    {name = "Qubes OS"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sphinx (>=8.2.3,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
sphinx = "^8.2.3"
sphinx-autobuild = "^2024.10.3"
sphinx-lint = "^1.0.0"
sphinx-reredirects = "^1.0.0"
sphinxnotes-strike = "^1.2.1"
sphinx-rtd-theme = "^3.0.2"

